Feat/loja
S-RPG/core pull request #25
Opened 2023-06-30 03:16 UTC by gSantiago22

Classe Loja praticamente finalizada pronta para começar a integrar a main do repositório

2023-06-30 03:37 UTC, DaviClark approved these changes

2023-06-30 21:14 UTC, iamcalegari requested changes

2023-06-30 21:14 UTC, iamcalegari commented on src/classes/loja/loja.hpp
Como você está pretendendo utilizar Templates para sua classe, a forma correta de se organizar o código é escrevendo tanto a sua **declaração** quanto a sua **definição** em um mesmo arquivo, no caso em um `.hpp`. Como diz o artigo [**Source code organization (C++ Templates)**](https://learn.microsoft.com/en-us/cpp/cpp/source-code-organization-cpp-templates?view=msvc-170),  [**Why can’t I separate the definition of my templates class from its declaration and put it inside a .cpp file?**](https://isocpp.org/wiki/faq/templates#templates-defn-vs-decl) e [**How can I avoid linker errors with my template functions?** ](https://learn.microsoft.com/en-us/cpp/cpp/source-code-organization-cpp-templates?view=msvc-170).

Separar o código como de costume vai gerar erros no compilador.

2023-07-06 23:48 UTC, iamcalegari approved these changes

2023-07-06 23:48 UTC, merged